sudo: required
services:
  - docker

before_install:
  - docker build -t ebenezer/docker-react -f Dockerfile.dev .

script:
  - docker run --env CI=true ebenezer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-188244996842"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"